version: '3.8'

services:
  frontend:
    build:
      context: ./game-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./game-frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:3001
      # Optional: help Vite detect changes in Docker on some hosts
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./game-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./game-backend:/app
    env_file:
      - ./game-backend/.env
    environment:
      - NODE_ENV=development
    command: npm run dev

networks:
  default:
    driver: bridge
