version: '3.8'

services:
  frontend:
    build:
      context: ./game-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./game-frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:3001
    depends_on:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./game-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./game-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
